version: '3'

services:
  phpfpm:
    image: adhocore/phpfpm:7.4
    container_name: '${PROJECT_NAME}-phpfpm'
    restart: always
    volumes:
      - ./app:/var/www/html
      - ./conf/php:/usr/local/etc/php/custom.d
    ports:
      - 9000:9000
    links:
      - mysql
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
  nginx:
    image: nginx:latest
    restart: always
    container_name: ${PROJECT_NAME}-nginx
    ports:
      - 80:80
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./app:/var/www/html
      - ./logs/nginx:/var/log/nginx
    links:
      - phpfpm
  mysql:
    image: mysql
    restart: always
    container_name: ${PROJECT_NAME}-mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
      - ./conf/mysql:/etc/mysql/conf.d
      - ./logs/mysql:/var/log/mysql
  adminer:
    container_name: ${PROJECT_NAME}-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080